### ISSUE TITLE
Add more helpful error messages when generating a multilang site

### ISSUE THREAD

**Issue by Jones-S** [wearelucid/lucid-nuxt-2021#193]
https://github.com/wearelucid/zfv-gastro-unibe/blob/main/graphql/scripts/fetchRoutesToBeGenerated.js#L14

This is how things look more or less correct.
In the boilerplate:
we have this:
https://github.com/wearelucid/lucid-nuxt-2021/blob/main/graphql/scripts/fetchRoutesToBeGenerated.js#L14

When generating you get this error:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/7059580/154106429-6aa6c444-7dd1-4585-86c6-d6917df79cd6.png">

> Fetching routes to generate from  http://zfv-cms.nitro/api                                                                                                                                               > 17:29:21
>
>  ERROR  TypeError: Cannot read properties of null (reading 'match')                                                                                                                                           >17:29:22
>
 > at _default (graphql/scripts/fetchRoutesToBeGenerated.js:36:11)
>  at processTicksAndRejections (node:internal/process/task_queues:96:5)
 > at async routes (nuxt.config.js:101:25)
>  at async AsyncCache.load [as _load] (node_modules/@nuxtjs/sitemap/lib/cache.js:18:22)

Instead of wasting 10min of debugging an error message here:
https://github.com/wearelucid/lucid-nuxt-2021/blob/main/graphql/scripts/fetchRoutesToBeGenerated.js#L36

with a hint just like above
`"❌ Couldn't get routes from CMS. Is API_URL defined in .env and your GraphQL endpoint working?"`
woudl be awesome.

**Comment by marcoeh** [comment]
is this still an issue @Jones-S ?
